/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated.relatorios'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated.perfil'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAtivosRouteImport } from './routes/_authenticated.ativos'
import { Route as AuthenticatedAdministracaoRouteImport } from './routes/_authenticated.administracao'
import { Route as AuthenticatedAtivosIndexRouteImport } from './routes/_authenticated.ativos.index'
import { Route as AuthenticatedAtivosNovoRouteImport } from './routes/_authenticated.ativos.novo'
import { Route as AuthenticatedAtivosNotebooksRouteImport } from './routes/_authenticated.ativos.notebooks'
import { Route as AuthenticatedAtivosImpressorasRouteImport } from './routes/_authenticated.ativos.impressoras'
import { Route as AuthenticatedAtivosComputadoresRouteImport } from './routes/_authenticated.ativos.computadores'
import { Route as AuthenticatedAtivosIdRouteImport } from './routes/_authenticated.ativos.$id'
import { Route as AuthenticatedAtivosIdIndexRouteImport } from './routes/_authenticated.ativos.$id.index'
import { Route as AuthenticatedAtivosIdEditarRouteImport } from './routes/_authenticated.ativos.$id.editar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAtivosRoute = AuthenticatedAtivosRouteImport.update({
  id: '/ativos',
  path: '/ativos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdministracaoRoute =
  AuthenticatedAdministracaoRouteImport.update({
    id: '/administracao',
    path: '/administracao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAtivosIndexRoute =
  AuthenticatedAtivosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAtivosRoute,
  } as any)
const AuthenticatedAtivosNovoRoute = AuthenticatedAtivosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AuthenticatedAtivosRoute,
} as any)
const AuthenticatedAtivosNotebooksRoute =
  AuthenticatedAtivosNotebooksRouteImport.update({
    id: '/notebooks',
    path: '/notebooks',
    getParentRoute: () => AuthenticatedAtivosRoute,
  } as any)
const AuthenticatedAtivosImpressorasRoute =
  AuthenticatedAtivosImpressorasRouteImport.update({
    id: '/impressoras',
    path: '/impressoras',
    getParentRoute: () => AuthenticatedAtivosRoute,
  } as any)
const AuthenticatedAtivosComputadoresRoute =
  AuthenticatedAtivosComputadoresRouteImport.update({
    id: '/computadores',
    path: '/computadores',
    getParentRoute: () => AuthenticatedAtivosRoute,
  } as any)
const AuthenticatedAtivosIdRoute = AuthenticatedAtivosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAtivosRoute,
} as any)
const AuthenticatedAtivosIdIndexRoute =
  AuthenticatedAtivosIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAtivosIdRoute,
  } as any)
const AuthenticatedAtivosIdEditarRoute =
  AuthenticatedAtivosIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedAtivosIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/ativos': typeof AuthenticatedAtivosRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/ativos/$id': typeof AuthenticatedAtivosIdRouteWithChildren
  '/ativos/computadores': typeof AuthenticatedAtivosComputadoresRoute
  '/ativos/impressoras': typeof AuthenticatedAtivosImpressorasRoute
  '/ativos/notebooks': typeof AuthenticatedAtivosNotebooksRoute
  '/ativos/novo': typeof AuthenticatedAtivosNovoRoute
  '/ativos/': typeof AuthenticatedAtivosIndexRoute
  '/ativos/$id/editar': typeof AuthenticatedAtivosIdEditarRoute
  '/ativos/$id/': typeof AuthenticatedAtivosIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/ativos/computadores': typeof AuthenticatedAtivosComputadoresRoute
  '/ativos/impressoras': typeof AuthenticatedAtivosImpressorasRoute
  '/ativos/notebooks': typeof AuthenticatedAtivosNotebooksRoute
  '/ativos/novo': typeof AuthenticatedAtivosNovoRoute
  '/ativos': typeof AuthenticatedAtivosIndexRoute
  '/ativos/$id/editar': typeof AuthenticatedAtivosIdEditarRoute
  '/ativos/$id': typeof AuthenticatedAtivosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/administracao': typeof AuthenticatedAdministracaoRoute
  '/_authenticated/ativos': typeof AuthenticatedAtivosRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/ativos/$id': typeof AuthenticatedAtivosIdRouteWithChildren
  '/_authenticated/ativos/computadores': typeof AuthenticatedAtivosComputadoresRoute
  '/_authenticated/ativos/impressoras': typeof AuthenticatedAtivosImpressorasRoute
  '/_authenticated/ativos/notebooks': typeof AuthenticatedAtivosNotebooksRoute
  '/_authenticated/ativos/novo': typeof AuthenticatedAtivosNovoRoute
  '/_authenticated/ativos/': typeof AuthenticatedAtivosIndexRoute
  '/_authenticated/ativos/$id/editar': typeof AuthenticatedAtivosIdEditarRoute
  '/_authenticated/ativos/$id/': typeof AuthenticatedAtivosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/administracao'
    | '/ativos'
    | '/dashboard'
    | '/perfil'
    | '/relatorios'
    | '/ativos/$id'
    | '/ativos/computadores'
    | '/ativos/impressoras'
    | '/ativos/notebooks'
    | '/ativos/novo'
    | '/ativos/'
    | '/ativos/$id/editar'
    | '/ativos/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/administracao'
    | '/dashboard'
    | '/perfil'
    | '/relatorios'
    | '/ativos/computadores'
    | '/ativos/impressoras'
    | '/ativos/notebooks'
    | '/ativos/novo'
    | '/ativos'
    | '/ativos/$id/editar'
    | '/ativos/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/administracao'
    | '/_authenticated/ativos'
    | '/_authenticated/dashboard'
    | '/_authenticated/perfil'
    | '/_authenticated/relatorios'
    | '/_authenticated/ativos/$id'
    | '/_authenticated/ativos/computadores'
    | '/_authenticated/ativos/impressoras'
    | '/_authenticated/ativos/notebooks'
    | '/_authenticated/ativos/novo'
    | '/_authenticated/ativos/'
    | '/_authenticated/ativos/$id/editar'
    | '/_authenticated/ativos/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ativos': {
      id: '/_authenticated/ativos'
      path: '/ativos'
      fullPath: '/ativos'
      preLoaderRoute: typeof AuthenticatedAtivosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administracao': {
      id: '/_authenticated/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AuthenticatedAdministracaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ativos/': {
      id: '/_authenticated/ativos/'
      path: '/'
      fullPath: '/ativos/'
      preLoaderRoute: typeof AuthenticatedAtivosIndexRouteImport
      parentRoute: typeof AuthenticatedAtivosRoute
    }
    '/_authenticated/ativos/novo': {
      id: '/_authenticated/ativos/novo'
      path: '/novo'
      fullPath: '/ativos/novo'
      preLoaderRoute: typeof AuthenticatedAtivosNovoRouteImport
      parentRoute: typeof AuthenticatedAtivosRoute
    }
    '/_authenticated/ativos/notebooks': {
      id: '/_authenticated/ativos/notebooks'
      path: '/notebooks'
      fullPath: '/ativos/notebooks'
      preLoaderRoute: typeof AuthenticatedAtivosNotebooksRouteImport
      parentRoute: typeof AuthenticatedAtivosRoute
    }
    '/_authenticated/ativos/impressoras': {
      id: '/_authenticated/ativos/impressoras'
      path: '/impressoras'
      fullPath: '/ativos/impressoras'
      preLoaderRoute: typeof AuthenticatedAtivosImpressorasRouteImport
      parentRoute: typeof AuthenticatedAtivosRoute
    }
    '/_authenticated/ativos/computadores': {
      id: '/_authenticated/ativos/computadores'
      path: '/computadores'
      fullPath: '/ativos/computadores'
      preLoaderRoute: typeof AuthenticatedAtivosComputadoresRouteImport
      parentRoute: typeof AuthenticatedAtivosRoute
    }
    '/_authenticated/ativos/$id': {
      id: '/_authenticated/ativos/$id'
      path: '/$id'
      fullPath: '/ativos/$id'
      preLoaderRoute: typeof AuthenticatedAtivosIdRouteImport
      parentRoute: typeof AuthenticatedAtivosRoute
    }
    '/_authenticated/ativos/$id/': {
      id: '/_authenticated/ativos/$id/'
      path: '/'
      fullPath: '/ativos/$id/'
      preLoaderRoute: typeof AuthenticatedAtivosIdIndexRouteImport
      parentRoute: typeof AuthenticatedAtivosIdRoute
    }
    '/_authenticated/ativos/$id/editar': {
      id: '/_authenticated/ativos/$id/editar'
      path: '/editar'
      fullPath: '/ativos/$id/editar'
      preLoaderRoute: typeof AuthenticatedAtivosIdEditarRouteImport
      parentRoute: typeof AuthenticatedAtivosIdRoute
    }
  }
}

interface AuthenticatedAtivosIdRouteChildren {
  AuthenticatedAtivosIdEditarRoute: typeof AuthenticatedAtivosIdEditarRoute
  AuthenticatedAtivosIdIndexRoute: typeof AuthenticatedAtivosIdIndexRoute
}

const AuthenticatedAtivosIdRouteChildren: AuthenticatedAtivosIdRouteChildren = {
  AuthenticatedAtivosIdEditarRoute: AuthenticatedAtivosIdEditarRoute,
  AuthenticatedAtivosIdIndexRoute: AuthenticatedAtivosIdIndexRoute,
}

const AuthenticatedAtivosIdRouteWithChildren =
  AuthenticatedAtivosIdRoute._addFileChildren(
    AuthenticatedAtivosIdRouteChildren,
  )

interface AuthenticatedAtivosRouteChildren {
  AuthenticatedAtivosIdRoute: typeof AuthenticatedAtivosIdRouteWithChildren
  AuthenticatedAtivosComputadoresRoute: typeof AuthenticatedAtivosComputadoresRoute
  AuthenticatedAtivosImpressorasRoute: typeof AuthenticatedAtivosImpressorasRoute
  AuthenticatedAtivosNotebooksRoute: typeof AuthenticatedAtivosNotebooksRoute
  AuthenticatedAtivosNovoRoute: typeof AuthenticatedAtivosNovoRoute
  AuthenticatedAtivosIndexRoute: typeof AuthenticatedAtivosIndexRoute
}

const AuthenticatedAtivosRouteChildren: AuthenticatedAtivosRouteChildren = {
  AuthenticatedAtivosIdRoute: AuthenticatedAtivosIdRouteWithChildren,
  AuthenticatedAtivosComputadoresRoute: AuthenticatedAtivosComputadoresRoute,
  AuthenticatedAtivosImpressorasRoute: AuthenticatedAtivosImpressorasRoute,
  AuthenticatedAtivosNotebooksRoute: AuthenticatedAtivosNotebooksRoute,
  AuthenticatedAtivosNovoRoute: AuthenticatedAtivosNovoRoute,
  AuthenticatedAtivosIndexRoute: AuthenticatedAtivosIndexRoute,
}

const AuthenticatedAtivosRouteWithChildren =
  AuthenticatedAtivosRoute._addFileChildren(AuthenticatedAtivosRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdministracaoRoute: typeof AuthenticatedAdministracaoRoute
  AuthenticatedAtivosRoute: typeof AuthenticatedAtivosRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdministracaoRoute: AuthenticatedAdministracaoRoute,
  AuthenticatedAtivosRoute: AuthenticatedAtivosRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
