// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkieaxljrlocsuythjqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdraWVheGxqcmxvY3N1eXRoanF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIxMzg4MDQsImV4cCI6MjA5NzcxNDgwNH0.oZT2--R2N88nKYLa8L96KUpBVfyebFkBvW3ZM-JtvjQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});